{
  "hash": "5d3c0fb1cd7dbe806701ed7f5d6c6e3f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Wczesne Wykrywanie Ryzyka Zawału Serca\"\nsubtitle: \"Zapoznanie I Praca Z Danymi\"\nformat: html\neditor: visual\nwarning: false\n---\n\n## Rozpoczęcie\n\nKoniec z Lorem Ipsum. Test GitHub Desktop.\n\n### Biblioteki\n\n\n::: {.cell}\n\n:::\n\n\n### Zapoznanie z danymi\n\nWczytanie pliku z rozszerzeniem `csv` do zmiennej o nazwie `data`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read.csv2(\"data/badania.csv\", sep=\",\")\n```\n:::\n\n\nSprawdźmy jak wyglądają nasze dane. Użyjemy do tego funkcji `head()` oraz `tail()` do podglądu kilku pierwszych i ostatnich obserwacji w naszym zbiorze danych. Pierwsze 10 obserwacji ma postać:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(data)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| male| age| education| currentSmoker| cigsPerDay| BPMeds| prevalentStroke| prevalentHyp| diabetes| totChol|sysBP |diaBP |BMI   | heartRate| glucose| TenYearCHD|\n|----:|---:|---------:|-------------:|----------:|------:|---------------:|------------:|--------:|-------:|:-----|:-----|:-----|---------:|-------:|----------:|\n|    1|  39|         4|             0|          0|      0|               0|            0|        0|     195|106   |70    |26.97 |        80|      77|          0|\n|    0|  46|         2|             0|          0|      0|               0|            0|        0|     250|121   |81    |28.73 |        95|      76|          0|\n|    1|  48|         1|             1|         20|      0|               0|            0|        0|     245|127.5 |80    |25.34 |        75|      70|          0|\n|    0|  61|         3|             1|         30|      0|               0|            1|        0|     225|150   |95    |28.58 |        65|     103|          1|\n|    0|  46|         3|             1|         23|      0|               0|            0|        0|     285|130   |84    |23.1  |        85|      85|          0|\n|    0|  43|         2|             0|          0|      0|               0|            1|        0|     228|180   |110   |30.3  |        77|      99|          0|\n\n</div>\n:::\n:::\n\n\nNatomiast kilka ostatnich obserwcji nad którymi bedziemy pracować mają postać:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(data)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     | male| age| education| currentSmoker| cigsPerDay| BPMeds| prevalentStroke| prevalentHyp| diabetes| totChol|sysBP |diaBP |BMI   | heartRate| glucose| TenYearCHD|\n|:----|----:|---:|---------:|-------------:|----------:|------:|---------------:|------------:|--------:|-------:|:-----|:-----|:-----|---------:|-------:|----------:|\n|4235 |    1|  51|         3|             1|         43|      0|               0|            0|        0|     207|126.5 |80    |19.71 |        65|      68|          0|\n|4236 |    0|  48|         2|             1|         20|     NA|               0|            0|        0|     248|131   |72    |22    |        84|      86|          0|\n|4237 |    0|  44|         1|             1|         15|      0|               0|            0|        0|     210|126.5 |87    |19.16 |        86|      NA|          0|\n|4238 |    0|  52|         2|             0|          0|      0|               0|            0|        0|     269|133.5 |83    |21.47 |        80|     107|          0|\n|4239 |    1|  40|         3|             0|          0|      0|               0|            1|        0|     185|141   |98    |25.6  |        67|      72|          0|\n|4240 |    0|  39|         3|             1|         30|      0|               0|            0|        0|     196|133   |86    |20.91 |        85|      80|          0|\n\n</div>\n:::\n:::\n\n\nSpradźmy rozmiary naszej ramki danych. W tym celu posłużymy się funkcjami `nrow()` oraz `ncol()`, które zawracają odpowiednio **liczbę wierszy** oraz **liczbę kolumn**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4240\n```\n\n\n:::\n\n```{.r .cell-code}\nncol(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16\n```\n\n\n:::\n:::\n\n\nWidzimy że mamy ponad 4200 obserwacji i 16 zmiennych, które posłużą nam do stworzenia kilku modeli predykcyjnych i wyboru tego, który najlepiej będzie oceniał ryzyko zawału serca. Jest to naprawdę duży zasób danych, które mogą odpowiedzieć na wiele interesujących pytań. Nadszedł czas sprawdzić zmienne, które posiadamy. Użyjemy do tego funkcji `colnames().`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"male\"            \"age\"             \"education\"       \"currentSmoker\"  \n [5] \"cigsPerDay\"      \"BPMeds\"          \"prevalentStroke\" \"prevalentHyp\"   \n [9] \"diabetes\"        \"totChol\"         \"sysBP\"           \"diaBP\"          \n[13] \"BMI\"             \"heartRate\"       \"glucose\"         \"TenYearCHD\"     \n```\n\n\n:::\n:::\n\n\nOkazuje się, że nasz zbiór zawiera cenne informacje medyczne takie jak:\n\n1.  Tętno\n\n2.  BMI\n\n3.  Ciśnienie skurczowe i rozkurczowe\n\n4.  Poziom cholesterolu i glukozy\n\n5.  Informacje o tym, czy pacjent był palaczem, czy też nie\n\nDokładniej przyjrzymy się naszym zmiennym w dalszej części analizy zbioru danych. Wyjaśnimy dokładniej cechy poszczególnych kolumn zbioru danych oraz ich podstawowe statystyki. Czas sprawdzić podstawowe statystki dotyczące danych oraz to z jakimi typami danych będziemy pracować.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(data)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |     |\n|:------------------------|:----|\n|Name                     |data |\n|Number of rows           |4240 |\n|Number of columns        |16   |\n|_______________________  |     |\n|Column type frequency:   |     |\n|character                |3    |\n|numeric                  |13   |\n|________________________ |     |\n|Group variables          |None |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|sysBP         |         0|             1|   2|   5|     0|      234|          0|\n|diaBP         |         0|             1|   2|   5|     0|      146|          0|\n|BMI           |        19|             1|   2|   5|     0|     1364|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable   | n_missing| complete_rate|   mean|    sd|  p0| p25| p50| p75| p100|hist  |\n|:---------------|---------:|-------------:|------:|-----:|---:|---:|---:|---:|----:|:-----|\n|male            |         0|          1.00|   0.43|  0.50|   0|   0|   0|   1|    1|▇▁▁▁▆ |\n|age             |         0|          1.00|  49.58|  8.57|  32|  42|  49|  56|   70|▃▇▆▆▂ |\n|education       |       105|          0.98|   1.98|  1.02|   1|   1|   2|   3|    4|▇▆▁▃▂ |\n|currentSmoker   |         0|          1.00|   0.49|  0.50|   0|   0|   0|   1|    1|▇▁▁▁▇ |\n|cigsPerDay      |        29|          0.99|   9.01| 11.92|   0|   0|   0|  20|   70|▇▃▁▁▁ |\n|BPMeds          |        53|          0.99|   0.03|  0.17|   0|   0|   0|   0|    1|▇▁▁▁▁ |\n|prevalentStroke |         0|          1.00|   0.01|  0.08|   0|   0|   0|   0|    1|▇▁▁▁▁ |\n|prevalentHyp    |         0|          1.00|   0.31|  0.46|   0|   0|   0|   1|    1|▇▁▁▁▃ |\n|diabetes        |         0|          1.00|   0.03|  0.16|   0|   0|   0|   0|    1|▇▁▁▁▁ |\n|totChol         |        50|          0.99| 236.70| 44.59| 107| 206| 234| 263|  696|▆▇▁▁▁ |\n|heartRate       |         1|          1.00|  75.88| 12.03|  44|  68|  75|  83|  143|▂▇▃▁▁ |\n|glucose         |       388|          0.91|  81.96| 23.95|  40|  71|  78|  87|  394|▇▁▁▁▁ |\n|TenYearCHD      |         0|          1.00|   0.15|  0.36|   0|   0|   0|   0|    1|▇▁▁▁▂ |\n\n\n:::\n:::\n\n\nTak jak widać na powyższym raporcie, zaczytując dane otrzymujemy 3 zmienne typu `character` oraz 13 zmiennych typu `numeric`. Taki podział ze względu na typ zmiennych nie jest odpowiedni. Wszystkie cechy typu `character` mają w naszym przypadku błędne formatowanie. Dodatkowo będziemy musieli dodać nowe typy zmiennych takie jak `boolean` oraz `factor`, aby móc szybko i praktycznie pracować z danymi. Odpowiedni wybór typów zmiennych jest podstawowym krokiem rozpczynając analizę zbioru danych. Zrobimy to w następujący sposób.\n\nbadania_sorted \\<- badania\\[order(is.na(badania\\$glucose), decreasing = TRUE), \\]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbadania <- data |> \n  mutate(\n    sysBP = as.numeric(sysBP),\n    diaBP = as.numeric(diaBP),\n    BMI = as.numeric(BMI),\n    sex = factor(male, levels = c(0, 1), labels = c(\"Female\", \"Male\")),\n    education = factor(education, ordered = TRUE),\n    currentSmoker = factor(currentSmoker, labels = c(\"No\", \"Yes\")),\n    BPMeds = factor(BPMeds, labels = c(\"No\", \"Yes\")),\n    prevalentStroke = factor(prevalentStroke, labels = c(\"No\", \"Yes\")),\n    prevalentHyp = factor(prevalentHyp, labels = c(\"No\", \"Yes\")),\n    diabetes = factor(diabetes, labels = c(\"No\", \"Yes\")),\n    TenYearCHD = factor(TenYearCHD, labels = c(\"No\", \"Yes\"))\n  ) |> dplyr::select(-male)   \n\nbadania <- badania[order(is.na(badania$glucose), decreasing = TRUE), ]\n```\n:::\n\n\nW tym momencie wszystkie zmienne mają przypisane odpowiednie typy danych, co pozwoli zaoszczędzić czas podczas przeprowadzania obliczeń i analizy nad nimi. Dla wygody uporządkujemy teraz kolumny w odpowiedniej dla nas kolejności, tak aby informacje powiązane ze sobą były obok siebie (Np. zmienna `glucose` obok zmiennej `diabetes`)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbadania <- dplyr::select(badania, c(1, 16, 2, 10, 11, 13, 12, 9, 14, 8, 4, 3, 5:7, 15))\nhead(badania)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   | age|sex    |education | sysBP| diaBP| heartRate|   BMI| totChol| glucose|diabetes | cigsPerDay|currentSmoker |BPMeds |prevalentStroke |prevalentHyp |TenYearCHD |\n|:--|---:|:------|:---------|-----:|-----:|---------:|-----:|-------:|-------:|:--------|----------:|:-------------|:------|:---------------|:------------|:----------|\n|15 |  39|Female |2         | 114.0|  64.0|        85| 22.35|     226|      NA|No       |          9|Yes           |No     |No              |No           |No         |\n|22 |  43|Female |1         | 123.5|  77.5|        70| 29.89|     185|      NA|No       |          0|No            |No     |No              |No           |No         |\n|27 |  60|Female |1         | 110.0|  72.5|        65| 26.59|     260|      NA|No       |          0|No            |No     |No              |No           |No         |\n|43 |  52|Female |1         | 148.0|  92.0|        70| 25.09|      NA|      NA|No       |          0|No            |Yes    |No              |Yes          |Yes        |\n|55 |  39|Female |2         | 115.0|  75.0|        90| 22.54|     209|      NA|No       |         20|Yes           |No     |No              |No           |No         |\n|71 |  63|Female |4         | 164.5|  76.0|        70| 29.35|     248|      NA|No       |          0|No            |No     |No              |No           |No         |\n\n</div>\n:::\n:::\n\n\nZrobione. Teraz możemy przejść do wyjaśnienia zmiennych, aby było jasne z czym pracujemy oraz na czym możemy polegać podczas wykonywania analizy.\n\n### Opis i wyjaśnienie zmiennych\n\nPoniżej znajduje się tabela zawierająca wszystkie cechy wraz z ich wytłumaczeniem.\n\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| Zmienna           | Opis                                                                 | Jednostka                                                    | Typ         |\n+:=================:+:====================================================================:+:============================================================:+:===========:+\n| `age`             | Wiek (w latach)                                                      | Lata                                                         | `int`       |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `sex`             | Płeć (1 - Mężczyzna, 0 - Kobieta)                                    | Brak                                                         | `factor`    |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `education`       | Wykształcenie                                                        | Brak                                                         | `factor`    |\n|                   |                                                                      |                                                              |             |\n|                   | (1 - Brak ukończonej szkoły średniej,                                |                                                              |             |\n|                   |                                                                      |                                                              |             |\n|                   | 2 - Ukończona szkoła średnia,                                        |                                                              |             |\n|                   |                                                                      |                                                              |             |\n|                   | 3 - Nieukończone studia lub ukończona szkoła zawodowa,               |                                                              |             |\n|                   |                                                                      |                                                              |             |\n|                   | 4 - Wykształcenie Wyższe)                                            |                                                              |             |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `sysBP`           | Wartość ciśnienia skurczowego (Średnia ostatnich dwóch pomiarów)     | mmHg                                                         | `numerical` |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `diaBP`           | Wartość ciśnienia rozkurczowego (Średnia ostatnich dwóch pomiarów)   | mmHg                                                         | `numerical` |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `heartRate`       | Poziom tętna ()                                                      | Uderzeń na minutę                                            | `int`       |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `BMI`             | Wartość współczynnika BMI                                            | $\\displaystyle \\frac{\\text{masa (kg)}}{\\text{wzrost (m)}^2}$ | `float`     |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `totalChol`       | Wartość poziomu cholesterolu ()                                      | $\\displaystyle \\frac{\\text{mg}}{\\text{dL}}$                  | `int`       |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `glucose`         | Poziom glukozy we krwi ()                                            | $\\displaystyle \\frac{\\text{mg}}{\\text{dL}}$                  | `int`       |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `diabetes`        | Fakt czy pacjent jest cukrzykiem\\                                    | brak                                                         | `factor`    |\n|                   | (1 - Tak, 0 - Nie)                                                   |                                                              |             |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `cigsPerDay`      | Średnia liczba palonych dziennie papierosów                          | sztuki                                                       | `int`       |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `currentSmoker`   | Fakt czy pacjent jest palaczem\\                                      | brak                                                         | `factor`    |\n|                   | (1- Tak, 0 - Nie)                                                    |                                                              |             |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `BMPmeds`         | Fakt czy pacjent leczy się na nadciśnienie krwi (1 - Tak, 0 - Nie)   | brak                                                         | `factor`    |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `prevalentStroke` | Wskazuje czy pacjent przeżył udar mózgu. (1 - Tak, 0 - Nie)          | brak                                                         | `factor`    |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `prevalentHyp`    | Wskazuje czy u pacjenta występowało nadciśnienie.\\                   | brak                                                         | `factor`    |\n|                   | (1 - Tak, 0 - Nie)                                                   |                                                              |             |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n| `TenYearCHD`      | Wskazuje 10-letnie ryzyko wystąpienia choroby wieńcowej u pacjenta.\\ | brak                                                         | `factor`    |\n|                   | (1- Tak, 0-Nie)                                                      |                                                              |             |\n+-------------------+----------------------------------------------------------------------+--------------------------------------------------------------+-------------+\n\n### Uzupełnienie brakujących wartości\n\nZastanówmy się co zrobić z brakami danych w naszym zbiorze badań. Przedstawmy ilość wartości `NA` dla każdej zmiennej, w której takie wartości wystepują.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNA_count <- colSums(is.na(badania))[colSums(is.na(badania)) > 0] |> \n  data.frame()\n\nnames(NA_count) <- \"count\"\nNA_count$var = rownames(NA_count)\nrownames(NA_count) <- NULL\nNA_count <- select(NA_count, c(2,1))\n\np <- ggplot(NA_count, aes(x = var, y = count, fill = \"#fc9d03\")) +\n  geom_col(show.legend = FALSE) +\n  theme_ipsum_rc() +\n  geom_text(aes(label = count), vjust = -0.5) + \n  expand_limits(y = max(NA_count$count) * 1.1) +\n  labs(title = \"Liczba wartości NA w zmiennych\")\n\nggsave(\"images/plots/na_count_before.png\", p)\n```\n:::\n\n\n![](images/plots/na_count_before.png){fig-align=\"center\"}\n\nWidzimy, że mamy kilka zmiennych, które zawierają braki danych. Liczby wartośći `NA` w poszczególnych kolumnach są zazwyczaj mniejsze lub równe około 100, jedynym wyjątkiem z aż 388 wartościami `NA` jest zmienna `glucose` oznaczająca poziom glukozy we krwi pacjenta. Zanim uzupełnimy braki danych odpowiednią techniką spróbujemy dowiedzieć się w jaki sposób rozkładają się wartości `NA` tzn. czy braki te wystepują u różnych pacjentów, czy też jeden pacjent posiada brak informacji w więcej niż tylko jednej zmiennej.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNA_df <- data.frame(NA_w_wierszu = rowSums(is.na(badania))) |> \n  group_by(NA_w_wierszu) |> \n  summarise(liczebnosc = n())\n\np <- NA_df |> ggplot(aes(NA_w_wierszu, liczebnosc, fill = \"#fc9d03\")) +\n  geom_col(show.legend = FALSE) +\n  theme_ipsum_rc() +\n  geom_text(aes(label = liczebnosc), vjust = -0.5) + \n  expand_limits(y = max(NA_df$liczebnosc) * 1.1) +\n  labs(title = \"Liczba wartości NA w rekordach\")\n\nggsave(\"images/plots/NA_count_perRow.png\", p)\n```\n:::\n\n\n![](images/plots/NA_count.png){fig-align=\"center\"}\n\nDo uzupełniania wartości brakujących przyjeliśmy następującą metodykę:\n\n-   Rekordy posiadające dokładnie jedną wartość `NA` uzupełnimy na podstawie metody wielokrotnej imputacji\n\n-   Rekordy posiadające więcej niż jedną wartość `NA` odrzucamy, aby nie bazować na znacznie brakujących danych\n\nW zmiennej `badania` wybieramy te wiersze, w których znajduje się co najwyżej jedna wartość `NA`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbadania <- badania[rowSums(is.na(badania)) <= 1, ]\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nWizualizacja liczby brakujących danych ma postać:\n\n::: panel-tabset\n#### Po wczytaniu danych\n\n![](images/plots/na_count_before.png){fig-align=\"center\"}\n\n#### Po wstępnym usunięciu brakujących danych\n\n![](images/plots/na_count_after.png){fig-align=\"center\"}\n:::\n\nW tym momencie przeprowadzimy proces uzupełniania zmiennych przy pomocy funkcji `mice` - metodą wielokrotnej imputacji. Braki danych znajdują się w kolumnach o różnych typach zmiennych.\n\n**Zmienne kategoryczne:**\n\n-   `BPMeds`\n\n-   `education`\n\n**Zmienne numeryczne:**\n\n-   `BMI`\n\n-   `cigsPerDay`\n\n-   `glucose`\n\n-   `heartRate`\n\n-   `totChol`\n\nZe względu na typy zmiennych oraz rozkłady, jakimi te zmienne się charakteryzują decydujemy się użyć metodę `pmm` (Predictive Mean Matching) dla zmiennych numerycznych oraz metodę `logreg` dla `BPMeds` oraz `polr` dla `education`.\n\n**Uzasadnienie:** `pmm` zachowuje rozkłady i wybiera realne obserwacje jako wartości wejściowe, co jest szczególnie ważne przy zmiennych o rozkładzie ciągłym. Dla zmiennych kategorycznych używamy odpowiednich regresji klasyfikacyjnych w zależności od cech zmiennej.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstatystyki_przed <- describe(badania[NA_count$var])\nmetody <- make.method(badania)\n\nmetody[\"BPMeds\"] <- \"logreg\"        #\nmetody[\"education\"] <- \"polr\" \nmetody[\"BMI\"] <- \"pmm\"\nmetody[\"cigsPerDay\"] <- \"pmm\"\nmetody[\"glucose\"] <- \"pmm\"\nmetody[\"heartRate\"] <- \"pmm\"\nmetody[\"totChol\"] <- \"pmm\"\nuzupelnienia <- mice(badania,\n                m = 5,\n                method = metody,\n                seed = 2025)\nbadania <- complete(uzupelnienia)\nstatystyki_po <- describe(badania[NA_count$var])\n```\n:::\n\n\nPo uzupełnieniu brakujących wartości porównajmy statystyki dla naszych zmiennych.\n\n::: panel-tabset\n#### Przed uzupełnieniem danych\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(data.frame(t(statystyki_przed))[c(2:9,10:12), ], 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|         | education.| heartRate|      BMI|  totChol|  glucose| cigsPerDay|  BPMeds.|\n|:--------|----------:|---------:|--------:|--------:|--------:|----------:|--------:|\n|n        |   4086.000|  4178.000| 4166.000| 4170.000| 3848.000|   4156.000| 4128.000|\n|mean     |      1.980|    75.876|   25.798|  236.726|   81.962|      8.982|    1.029|\n|sd       |      1.020|    12.035|    4.080|   44.660|   23.962|     11.912|    0.168|\n|median   |      2.000|    75.000|   25.385|  234.000|   78.000|      0.000|    1.000|\n|trimmed  |      1.850|    75.194|   25.524|  234.666|   78.975|      6.871|    1.000|\n|mad      |      1.483|    10.378|    3.684|   42.995|   11.861|      0.000|    0.000|\n|min      |      1.000|    44.000|   15.540|  107.000|   40.000|      0.000|    1.000|\n|max      |      4.000|   143.000|   56.800|  696.000|  394.000|     70.000|    2.000|\n|range    |      3.000|    99.000|   41.260|  589.000|  354.000|     70.000|    1.000|\n|skew     |      0.688|     0.647|    0.991|    0.870|    6.211|      1.251|    5.604|\n|kurtosis |     -0.718|     0.914|    2.687|    4.107|   58.585|      1.038|   29.414|\n\n</div>\n:::\n:::\n\n\n#### Po uzupełnieniu danych\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(data.frame(t(statystyki_po))[c(2:8,10:12), ], 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|         | education.| heartRate|      BMI|  totChol|  glucose| cigsPerDay|  BPMeds.|\n|:--------|----------:|---------:|--------:|--------:|--------:|----------:|--------:|\n|n        |   4179.000|  4179.000| 4179.000| 4179.000| 4179.000|   4179.000| 4179.000|\n|mean     |      1.978|    75.872|   25.802|  236.748|   81.817|      9.029|    1.029|\n|sd       |      1.020|    12.036|    4.080|   44.681|   23.749|     11.913|    0.167|\n|median   |      2.000|    75.000|   25.400|  234.000|   78.000|      0.000|    1.000|\n|trimmed  |      1.848|    75.190|   25.529|  234.678|   78.917|      6.928|    1.000|\n|mad      |      1.483|    10.378|    3.692|   42.995|   11.861|      0.000|    0.000|\n|min      |      1.000|    44.000|   15.540|  107.000|   40.000|      0.000|    1.000|\n|range    |      3.000|    99.000|   41.260|  589.000|  354.000|     70.000|    1.000|\n|skew     |      0.691|     0.647|    0.986|    0.870|    6.397|      1.241|    5.642|\n|kurtosis |     -0.715|     0.913|    2.672|    4.092|   62.373|      1.011|   29.839|\n\n</div>\n:::\n:::\n\n:::\n\nSprawdzając podstawowe statystki widzimy, że uzupełniając dane zachowaliśmy ich strukturę. Różnica pomiędzy wartościami statystyk polega najczęściej na zmianie części tysięcznych lub setnych, więc wartości `NA` zostały bardzo dobrze odwzorowane. Teraz możemy zrobić analizę wstępną naszego zbioru danych, aby następnie przejść do stworzenia modeli predykcyjnych oraz głębszej analizy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbadania <- mutate(badania, ID = 1:nrow(badania))\nzdrowi <- badania |> \n  subset(TenYearCHD == \"No\")\n\nchorzy <- badania |> \n  subset(TenYearCHD == \"Yes\")\n```\n:::\n\n\n### Wstępna Analiza\n\n#### Statystyki\n\n\n::: {.cell}\n\n:::\n\n\n#### Funkcja tworzenia wykresów\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzmienna_wykres <- function(dane, typ_zmiennej, typ_wykresu) {\n  my_plots = list()\n  if (typ_zmiennej == \"kategoryczna\") {\n    dane <- dane |> \n      dplyr::select(where(is.factor))\n  } else if (typ_zmiennej == \"numeryczna\") {\n    dane <- dane |> \n      dplyr::select(where(is.numeric))\n  } else {\n    # nic nie robimy\n  }\n  \n  for (i in 1:ncol(dane)) {\n    kolumna <- colnames(dane)[i]\n    if (typ_wykresu == \"barplot\") {\n    p <- ggplot(dane, aes(x = !!sym(kolumna), fill = !!sym(kolumna))) +\n      geom_bar(show.legend = FALSE) +\n      theme_ipsum_rc() +\n      ggtitle(kolumna) +\n      scale_fill_manual(values = c(\"#6AAED9\", \"#F2A391\", \"#2C5DBF\", \"#F25041\"))\n      \n    \n    } else if (typ_wykresu == \"pie\") {\n      p <- dane %>%\n        dplyr::count(!!sym(kolumna)) %>%\n        ggplot(aes(x = \"\", y = n, fill = !!sym(kolumna))) +\n        geom_bar(stat = \"identity\", width = 1, color = \"white\") +\n        coord_polar(theta = \"y\") +\n        theme_void() +\n        ggtitle(kolumna) +\n        scale_fill_manual(values = c(\"#6AAED9\", \"#F2A391\", \"#2C5DBF\", \"#F25041\"))\n      \n    } else if (typ_wykresu == \"histogram\") {\n      p <- ggplot(dane, aes(x = !!sym(kolumna))) +\n        geom_histogram(bins = 20, show.legend = FALSE, fill = \"#6AAED9\") +\n        theme_ipsum_rc() +\n        ggtitle(kolumna)\n        \n      \n    } else if (typ_wykresu == \"violin\") {\n      p <- ggplot(dane, aes(x = \"\", y = !!sym(kolumna), fill = \"#6AAED9\")) +\n        geom_violin(show.legend = FALSE) +\n        theme_ipsum_rc() +\n        ggtitle(kolumna) +\n        scale_fill_manual(values = c(\"#6AAED9\", \"#F2A391\", \"#2C5DBF\", \"#F25041\"))\n    } else {\n      next  # pomiń jeśli nieznany typ wykresu\n    }\n    my_plots[[i]] <- p\n  } \n\n  \ngotowy_wykres_1 <- (my_plots[[1]] + my_plots[[2]]) / (my_plots[[3]] + my_plots[[4]]) \ngotowy_wykres_2 <- (my_plots[[5]] + my_plots[[6]]) / (my_plots[[7]] + my_plots[[8]])\nggsave(paste0(\"images/plots/\", typ_zmiennej, \"_\", typ_wykresu, \"1.png\"), gotowy_wykres_1)\nggsave(paste0(\"images/plots/\", typ_zmiennej, \"_\", typ_wykresu, \"2.png\"), gotowy_wykres_2)\n}\n```\n:::\n\n\nTak zbudowana funkcja pozwala nam na generowanie wykresów w zależności od:\n\n-   Typu zmiennej\n\n-   Typu wykresu\n\nDzięki temu możemy szybko i prosto uzyskać wiele wizualizacji na temat interesujących nas zmiennych. Zdecydowaliśmy się przedstawić nasze zmienne z podziałem na:\n\n1.  Zmienne typu kategorycznego, przedstawiając liczebność ogólną oraz względem siebie, za pomocą wykresów `barplot` oraz `pie`.\n\n<!-- -->\n\n2.  Zmienne typu numerycznego, przedstawiając gęstośc oraz rozkład zmiennej, za pomocą wykresów `violin` oraz `histogram`\n\nPoniżej przedstawiamy efekty naszej pracy, gdzie przeanalizujemy poszczególne zmienne.\n\n#### Zmienne Kategoryczne\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzmienna_wykres(badania, \"kategoryczna\", \"barplot\")\nzmienna_wykres(badania, \"kategoryczna\", \"pie\")\n```\n:::\n\n\n::: panel-tabset\n## Barplot\n\n![](images/plots/kategoryczna_barplot1.png){fig-align=\"center\"}\n\n![](images/plots/kategoryczna_barplot2.png){fig-align=\"center\"}\n\n## Pie\n\n![](images/plots/kategoryczna_pie1.png){fig-align=\"center\"}\n\n![](images/plots/kategoryczna_pie2.png){fig-align=\"center\"}\n:::\n\nPo przeanalizowaniu wykresów nasuwają się nastepujące wnioski:\n\n-   Analizujemy zbiór ponad 4.000 osób, w którym kobiety lekko przewyższają swoją liczebnością mężczyzn.\n\n-   Wraz z poziomem wykształcenia zmniejsza się liczba osób w danej kategorii wykształcenia. Osób bez ukończonej szkoły średniej jest około 1750, stopniowo zmniejszając się do 500 osób z wykształceniem wyższym. Wśród naszych danych przeważają osoby bez wykształcenia lub jedynie z wykształceniem średnim.\n\n-   Podział na osoby palące i niepalące jest jednakowy. Obie grupy zawierają około 2.000 osób.\n\n-   Grupy osób w których skład wchodzą osoby z cukrzycą, osoby leczące nadciśnienie krwi oraz osoby, które przeżyły udar mózgu są bardzo nieliczne. Ograniczają się maksymalnie do kilkudziesięciu osób. Mimo wszystko osoby te mogą dostarczyć wiele cennych informacji w dalszej analizie ryzyka choroby serca.\n\n-   Bazujemy na danych w których stosunek liczby osób, u których nie występowało nadciśnienie do liczby osób u których nadciśnienie występowało jest równe w przybliżeniu 2:1.\n\n-   Zmienna predykcyjna `TenYearCHD` przewiduje potencjalne ryzyko choroby serca dla ponad 500 osób, co stanowi około 12.5% liczby wszystkich badanych. Oznacza to, że średnio co 8 badana osoba jest kwalifikowana w grupie ryzyka.\n\n#### Zmienne Numeryczne\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzmienna_wykres(badania, \"numeryczna\", \"violin\")\nzmienna_wykres(badania, \"numeryczna\", \"histogram\")\n```\n:::\n\n\n::: panel-tabset\n## Violin\n\n![](images/plots/numeryczna_violin1.png){fig-align=\"center\"}\n\n![](images/plots/numeryczna_violin2.png){fig-align=\"center\"}\n\n## Histogram\n\n![](images/plots/numeryczna_histogram1.png){fig-align=\"center\"}\n\n![](images/plots/numeryczna_histogram2.png){fig-align=\"center\"}\n:::\n\nPo przeanalizowaniu wykresów nasuwają się nastepujące wnioski:\n\n-   Badamy grupę osób, w której większość osób ma od 35 do 65 lat.\n\n-   Ciśnienie rozkurczowe zawiera się głównie w przedziale \\<70; 90\\> natomiast ciśnienie skurczowe w przedziale \\<115; 140\\>\n\n-   Najczęściej badane osoby posiadają tętno serca na poziomie 70-80 uderzeń na minutę.\n\n-   Interesujący jest rozkład zmiennej `cigsPerDay`. Widać znaczący wzrost wystąpień osób palących 20 papierosów dziennie. Dokładnie taka liczba papierosów znajduje się w pojedyńczej paczce. Możemy zatem przyjąć, że dla wielu osób codziennym nawykiem jest wypalenie dokładnie całej paczki w trakcie dnia.\n\n-   Zmienne cechują się niesymetrycznym rozkładem, dodatkowo zaburzone są rozkłady dla zmiennej `age` oraz `cigsPerDay`.\n\n-   Większość zmiennych jest prawostronnie asymetryczna, ciężko mówić o normalności rozkładów ze względu na obecność wartości odstających, które są powszechne wśród danych medycznych.\n\n#### Zależności pomiędzy zmiennymi\n\nWśród naszych zmiennych mogą istnieć zależności liniowe. W celu sprawdzenia tego faktu stworzymy macierz korelacji, aby przedstawić jak wygląda korelacja pomiędzy poszczególnymi zmiennymi. Posłużymy się w tym celu zmiennymi numerycznymi.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_mat <- badania %>% \n  select(where(is.numeric)) %>% \n  cor()\n\np <- ggcorrplot(\n    cor_mat,\n    lab = TRUE,               \n    type = \"lower\",           \n    hc.order = TRUE,          #\n    outline.col = \"white\",\n    ggtheme = ggplot2::theme_minimal(),\n    colors = c(\"#6AAED9\", \"white\", \"#F25041\") \n)\nggsave(\"images/plots/macierz_korelacji.jpg\", p)\n```\n:::\n\n\n![](images/plots/macierz_korelacji.jpg){fig-align=\"center\"}\n\nWidzimy, że istnieje duża korelacja równa 0.78 pomiędzy zmiennymi `sysBP` oraz `diaBP`. Nie powinno nas to specjalnie dziwić, ponieważ wartość ciśnienia rozkurczowego ma bezpośredni wypływ na wartość ciśnienia skurczowego. Dodatkowo poziom BMI a co za tym idzie - nasza waga ma wpływ na wartośc ciśnienia rozkurczowego oraz skurczowego. W oczy może rzucić nam się również wartość korelacji na poziomie -0.19 między zmienną `age` oraz `cigsPerDay`, która oznacza, że wraz z wiekiem palimy coraz mniej papierosów dziennie. Nie są to jednak wysokie wartości współczynnika korelacji, więc nie możemy powiedzieć, że pomiędzy tymi zmiennymi istnieje statystycznie istotna korelacja. Możemy jedna informacje traktować jako wskazówki podczas dalszej analizy i zgłębić analizę w kierunku tych zmiennych.\n\n#### Relacja pomiędzy `diaBP` oraz `sysBP`\n\nSprawdźmy jak będzie wyglądać zestawienie wartości ciśnienia skurczowego od wartości ciśnienia rozkurczowego, dodatkowo dodamy kilka czynników, które dotakowo pokażą zależności pomiędzy większą liczbą zmiennych.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(badania, aes(x = diaBP, y = sysBP, color = sex, shape = sex)) +\n  geom_point() +\n  theme_ipsum_rc() +\n  ggtitle(\"sysBP ~ diaBP\") +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\", \"#2C5DBF\", \"#F25041\")) +\n  theme(legend.position = \"bottom\")\n\nggsave(\"images/plots/sysBP_diaBP_bySex_point.jpg\", p1)\n```\n:::\n\n\n![](images/plots/sysBP_diaBP_bySex_point.jpg){fig-align=\"center\"}\n\nZe względu na dużą liczbę rekordów, punkty zaznaczone na wykresie typu `scatter plot` tworzą masywną chmurę punktów, utrudniając interpretację. Aby ułatwić analizę na podstawie wykresu posłużymy się wykresami gęstości porównując dodatkowo wpływ innych zmiennych na wartość ciśnienia rozkurczowego oraz skurczowego.\n\n#### Ciśnienie rozkurczowe\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(badania, aes(x = diaBP, color = sex)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  ggtitle(\"sysBP ~ diaBP\") +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\")) +\n  theme(legend.position = \"bottom\")\n\np2 <- ggplot(badania, aes(x = diaBP, color = education)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  ggtitle(\"sysBP ~ diaBP\") +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\", \"#2C5DBF\", \"#F25041\")) +\n  theme(legend.position = \"bottom\")\n\np3 <- ggplot(badania, aes(x = diaBP, color = currentSmoker)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  ggtitle(\"sysBP ~ diaBP\") +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\", \"#2C5DBF\", \"#F25041\")) +\n  theme(legend.position = \"bottom\")\n\nggsave(\"images/plots/diaBP_bySex.jpg\", p1)\nggsave(\"images/plots/diaBP_byEducation.jpg\", p2)\nggsave(\"images/plots/diaBP_byCurrentSmoker.jpg\", p3)\n```\n:::\n\n\n::: panel-tabset\n### Względem zmiennej sex\n\n![](images/plots/diaBP_bySex.jpg){fig-align=\"center\"}\n\n### Względem zmiennej education\n\n![](images/plots/diaBP_byEducation.jpg){fig-align=\"center\"}\n\n### Względem zmiennej currentSmoker\n\n![](images/plots/diaBP_byCurrentSmoker.jpg){fig-align=\"center\"}\n:::\n\nanaliza::\n\n#### Ciśnienie skurczowe\n\nAnalogicznie postepujemy dla zmiennej `sysBP`. Pamiętamy że omawiane zmienne są silnie ze sobą skorelowane, więc spodziewamy się podobnych rezultatów.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(badania, aes(x = sysBP, color = sex)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  ggtitle(\"sysBP ~ diaBP\") +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\")) +\n  theme(legend.position = \"bottom\")\n\np2 <- ggplot(badania, aes(x = sysBP, color = education)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  ggtitle(\"sysBP ~ diaBP\") +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\", \"#2C5DBF\", \"#F25041\")) +\n  theme(legend.position = \"bottom\")\n\np3 <- ggplot(badania, aes(x = sysBP, color = currentSmoker)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  ggtitle(\"sysBP ~ diaBP\") +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\", \"#2C5DBF\", \"#F25041\")) +\n  theme(legend.position = \"bottom\")\n\nggsave(\"images/plots/sysBP_bySex.jpg\", p1)\nggsave(\"images/plots/sysBP_byEducation.jpg\", p2)\nggsave(\"images/plots/sysBP_byCurrentSmoker.jpg\", p3)\n```\n:::\n\n\n::: panel-tabset\n### Względem zmiennej sex\n\n![](images/plots/sysBP_bySex.jpg){fig-align=\"center\"}\n\n### Względem zmiennej education\n\n![](images/plots/sysBP_byEducation.jpg){fig-align=\"center\"}\n\n### Względem zmiennej currentSmoker\n\n![](images/plots/sysBP_byCurrentSmoker.jpg){fig-align=\"center\"}\n:::\n\nanaliza::\n\n#### Zakres pracy serca, a ryzyko zawału\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- badania |> \n  mutate(range_diff = sysBP - diaBP) |> \n  arrange(range_diff) |> \n  ggplot(aes(x = range_diff, color = TenYearCHD)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\"))\n\nggsave(\"images/plots/range_density.jpg\", p)\n```\n:::\n\n\n![](images/plots/range_density.jpg){fig-align=\"center\"}\n\n#### Wartość ciśnienia skurczowego jako czynnik ryzyka\n\n:analiza::\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- badania |> \n  ggplot(aes(x = TenYearCHD, y = sysBP, color = sex)) +\n  geom_boxplot() +\n  theme_ipsum_rc() +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- badania |> \n  ggplot(aes(x = sysBP, color = TenYearCHD)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\"))\n```\n:::\n\n\n### Analiza wartości tętna\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- badania |> \n  ggplot(aes(x = heartRate, fill = TenYearCHD)) +\n  geom_histogram(binwidth = 5) +\n  theme_ipsum_rc() +\n  scale_fill_manual(values = c(\"#6AAED9\", \"#F2A391\"))\np\n```\n\n::: {.cell-output-display}\n![](dane_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- badania |> \n  ggplot(aes(x = heartRate)) +\n  geom_density(color = \"#6AAED9\", lwd = 1.2) +\n  stat_function(\n    fun = dnorm,\n    args = list(mean = mean(badania$heartRate), sd = sd(badania$heartRate)),\n    linewidth = 1.2,\n    col = \"#F25041\"\n  ) +\n  theme_ipsum_rc()\np\n```\n\n::: {.cell-output-display}\n![](dane_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- badania |> \n  ggplot(aes(x = TenYearCHD, y = heartRate, color = sex)) +\n  geom_boxplot() +\n  theme_ipsum_rc() +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\"))\n\np2 <- badania |> \n  ggplot(aes(x = TenYearCHD, y = heartRate, color = currentSmoker)) +\n  geom_boxplot() +\n  theme_ipsum_rc() +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\"))\n\np3 <- badania |> \n  ggplot(aes(x = TenYearCHD, y = heartRate, color = BPMeds)) +\n  geom_boxplot() +\n  theme_ipsum_rc() +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\"))\n\np1; p2; p3\n```\n\n::: {.cell-output-display}\n![](dane_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](dane_files/figure-html/unnamed-chunk-31-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](dane_files/figure-html/unnamed-chunk-31-3.png){width=672}\n:::\n:::\n\n\n::: panel-tabset\n#### \n:::\n\n#### BPMeds, a ciśnienie\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- badania |> \n  ggplot(aes(x = sysBP, color = BPMeds)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\"))\n\np2 <- badania |> \n  ggplot(aes(x = diaBP, color = BPMeds)) +\n  geom_density(lwd = 1.2) +\n  theme_ipsum_rc() +\n  scale_color_manual(values = c(\"#6AAED9\", \"#F2A391\"))\n\np1;p2\n```\n\n::: {.cell-output-display}\n![](dane_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](dane_files/figure-html/unnamed-chunk-32-2.png){width=672}\n:::\n:::\n\n\n::: panel-tabset\n:::\n\n#### Skutki palenia na układ krążenia\n\n\n::: {.cell}\n\n```{.r .cell-code}\nosoby_palace <- badania |> \n  subset(currentSmoker == \"Yes\")\n\nosoby_niepalace <- badania |> \n  subset(cigsPerDay == 0)\n\nnrow(osoby_palace)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2057\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(osoby_niepalace)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2122\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- badania |> \n  ggplot(aes(x = currentSmoker)) +\n  geom_bar() +\n  theme_ipsum_rc()\n\np2 <- badania |> \n  ggplot(aes(x = cigsPerDay)) +\n  geom_bar() +\n  theme_ipsum_rc()\n\np1; p2\n```\n\n::: {.cell-output-display}\n![](dane_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](dane_files/figure-html/unnamed-chunk-34-2.png){width=672}\n:::\n:::\n\n\n### Relacja pomiędzy zmienną `age`, a zmienną `cigsPerDay`\n\n\n::: {.cell}\n\n:::\n\n\n<div>\n\n![](images/article/to_use/picture_2.png){style=\"margin-top: 25px;\" fig-align=\"center\"}\n\n</div>\n",
    "supporting": [
      "dane_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}